### PR TITLE
Fixed HLA measurement date. Updated the measurement table

### LINKED ISSUE #259: update measurement time for hla imputed data to lower than observation period end date
The reason why achilles is not counting and Atlas is not showing is because hla measurement dates are over the observation period end dates. 

Steps to fix

- [x] Change `measurement_date` with respect to `BL_YEAR` and `BL_AGE`

### PR DESCRIPTION
**Pull request by shanmukhasampath**
This is for issue #259 

Fixed the HLA measurement date and time.

### CODE REVIEW

**Review by javier-gracia-tabuenca-tuni — COMMENTED** [review]
shoudnt it be the baseline date ?
when they donated the dna, as the hard coded date may be our of observation for some

File: 3_etl_code/ETL_Orchestration/sql/etl_hla_imputed_to_measurement.sql [hunk 1]
```diff
@@ -45,10 +45,16 @@ hla_imputed_source_code AS (
   SELECT hi.FINNGENID,
          hi.Allele,
          hi.HLAcode,
-         c.concept_id AS omop_concept_id
+         c.concept_id AS omop_concept_id, 
+         CASE
+              WHEN hi.BL_YEAR > EXTRACT(YEAR FROM CURRENT_DATE()) THEN '2024-12-18' # THIS IS ONLY FOR atlas-development
```
Comment (javier-gracia-tabuenca-tuni) [inline 3_etl_code/ETL_Orchestration/sql/etl_hla_imputed_to_measurement.sql]: is this a typo ? 
should it be 
fi.BL_YEAR
??

why is this different in atlas deb ?

Comment (shanmukhasampath) [reply 3_etl_code/ETL_Orchestration/sql/etl_hla_imputed_to_measurement.sql]: Hi @javier-gracia-tabuenca-tuni , yes it is `fi.BL_YEAR`. Also, this is because some of the dummy FINNGEIDs have BL_YEAR as 2033, 2049. This breaks the HLA cohort construction in Atlas-development side.
